import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}

        <Link href="/notes">Note </Link>
        <Link href="/notes/1">Note 1</Link>
        <Link href="/notes/2">Note 2</Link>
        <Link href="/pages">Page</Link>
      </body>
    </html>
  )
}
